services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: development
    command: cross-env NODE_ENV=development TZ=Asia/Ho_Chi_Minh ts-node-dev --respawn App.ts
    ports:
      - 4080:4080
